// Generated by gencpp from file serviec_demo/Greeting.msg
// DO NOT EDIT!


#ifndef SERVIEC_DEMO_MESSAGE_GREETING_H
#define SERVIEC_DEMO_MESSAGE_GREETING_H

#include <ros/service_traits.h>


#include <serviec_demo/GreetingRequest.h>
#include <serviec_demo/GreetingResponse.h>


namespace serviec_demo
{

struct Greeting
{

typedef GreetingRequest Request;
typedef GreetingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Greeting
} // namespace serviec_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::serviec_demo::Greeting > {
  static const char* value()
  {
    return "116e2074a4605229af423317e5dff099";
  }

  static const char* value(const ::serviec_demo::Greeting&) { return value(); }
};

template<>
struct DataType< ::serviec_demo::Greeting > {
  static const char* value()
  {
    return "serviec_demo/Greeting";
  }

  static const char* value(const ::serviec_demo::Greeting&) { return value(); }
};


// service_traits::MD5Sum< ::serviec_demo::GreetingRequest> should match 
// service_traits::MD5Sum< ::serviec_demo::Greeting > 
template<>
struct MD5Sum< ::serviec_demo::GreetingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::serviec_demo::Greeting >::value();
  }
  static const char* value(const ::serviec_demo::GreetingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::serviec_demo::GreetingRequest> should match 
// service_traits::DataType< ::serviec_demo::Greeting > 
template<>
struct DataType< ::serviec_demo::GreetingRequest>
{
  static const char* value()
  {
    return DataType< ::serviec_demo::Greeting >::value();
  }
  static const char* value(const ::serviec_demo::GreetingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::serviec_demo::GreetingResponse> should match 
// service_traits::MD5Sum< ::serviec_demo::Greeting > 
template<>
struct MD5Sum< ::serviec_demo::GreetingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::serviec_demo::Greeting >::value();
  }
  static const char* value(const ::serviec_demo::GreetingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::serviec_demo::GreetingResponse> should match 
// service_traits::DataType< ::serviec_demo::Greeting > 
template<>
struct DataType< ::serviec_demo::GreetingResponse>
{
  static const char* value()
  {
    return DataType< ::serviec_demo::Greeting >::value();
  }
  static const char* value(const ::serviec_demo::GreetingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVIEC_DEMO_MESSAGE_GREETING_H
