// Generated by gencpp from file path/myLaser.msg
// DO NOT EDIT!


#ifndef PATH_MESSAGE_MYLASER_H
#define PATH_MESSAGE_MYLASER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path
{
template <class ContainerAllocator>
struct myLaser_
{
  typedef myLaser_<ContainerAllocator> Type;

  myLaser_()
    : serial()  {
    }
  myLaser_(const ContainerAllocator& _alloc)
    : serial(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _serial_type;
  _serial_type serial;





  typedef boost::shared_ptr< ::path::myLaser_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path::myLaser_<ContainerAllocator> const> ConstPtr;

}; // struct myLaser_

typedef ::path::myLaser_<std::allocator<void> > myLaser;

typedef boost::shared_ptr< ::path::myLaser > myLaserPtr;
typedef boost::shared_ptr< ::path::myLaser const> myLaserConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path::myLaser_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path::myLaser_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'path': ['/home/tbf/projects/0425/code/catkin_ws/src/path/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path::myLaser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path::myLaser_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path::myLaser_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path::myLaser_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path::myLaser_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path::myLaser_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path::myLaser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d8b094b0dd476a7b3679b1db6012cbd9";
  }

  static const char* value(const ::path::myLaser_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd8b094b0dd476a7bULL;
  static const uint64_t static_value2 = 0x3679b1db6012cbd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::path::myLaser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path/myLaser";
  }

  static const char* value(const ::path::myLaser_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path::myLaser_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] serial \n\
";
  }

  static const char* value(const ::path::myLaser_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path::myLaser_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serial);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct myLaser_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path::myLaser_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path::myLaser_<ContainerAllocator>& v)
  {
    s << indent << "serial[]" << std::endl;
    for (size_t i = 0; i < v.serial.size(); ++i)
    {
      s << indent << "  serial[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.serial[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_MESSAGE_MYLASER_H
