// Generated by gencpp from file path/serial.msg
// DO NOT EDIT!


#ifndef PATH_MESSAGE_SERIAL_H
#define PATH_MESSAGE_SERIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace path
{
template <class ContainerAllocator>
struct serial_
{
  typedef serial_<ContainerAllocator> Type;

  serial_()
    : vk(0.0)
    , wk(0.0)  {
    }
  serial_(const ContainerAllocator& _alloc)
    : vk(0.0)
    , wk(0.0)  {
  (void)_alloc;
    }



   typedef float _vk_type;
  _vk_type vk;

   typedef float _wk_type;
  _wk_type wk;





  typedef boost::shared_ptr< ::path::serial_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path::serial_<ContainerAllocator> const> ConstPtr;

}; // struct serial_

typedef ::path::serial_<std::allocator<void> > serial;

typedef boost::shared_ptr< ::path::serial > serialPtr;
typedef boost::shared_ptr< ::path::serial const> serialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path::serial_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path::serial_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'path': ['/home/tbf/projects/0425/code/catkin_ws/src/path/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path::serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path::serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path::serial_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path::serial_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path::serial_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path::serial_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1d934fb5105682f89baa76d53ad978a";
  }

  static const char* value(const ::path::serial_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1d934fb5105682fULL;
  static const uint64_t static_value2 = 0x89baa76d53ad978aULL;
};

template<class ContainerAllocator>
struct DataType< ::path::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path/serial";
  }

  static const char* value(const ::path::serial_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path::serial_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vk\n\
float32 wk\n\
";
  }

  static const char* value(const ::path::serial_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path::serial_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vk);
      stream.next(m.wk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path::serial_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path::serial_<ContainerAllocator>& v)
  {
    s << indent << "vk: ";
    Printer<float>::stream(s, indent + "  ", v.vk);
    s << indent << "wk: ";
    Printer<float>::stream(s, indent + "  ", v.wk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_MESSAGE_SERIAL_H
